databases:
  - name: portabilis
    databaseName: portabilis
    user: portabilis

services:
  - type: web
    name: portabilis
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portabilis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
